#:schema https://rlbot.org/schemas/agent.json
[settings]
loadout_file = "loadout.toml"
name = "Element"
run_command = "uv run bot.py"
run_command_linux = "uv run bot.py"
agent_id = "Rangler/Element"

[details]
developer = "Rangler"
description = "A neural network trained with reinforcement learning to play 1v1."
fun_fact = "Element was trained with RLGym and has played more than 27 years of Rocket League!"
source_link = "https://github.com/VirxEC/Elementv5"
language = "rlgym"
tags = [ "1v1" ]
